# Generated by Django 5.1.3 on 2024-11-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votos',
            name='votos',
            field=models.IntegerField(default=0),
        ),
    ]
