# Generated by Django 5.1.3 on 2024-11-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_votos_votos'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotosCandidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('votos', models.IntegerField(default=0)),
                ('sessao', models.CharField(max_length=4)),
                ('zona', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Votos',
        ),
    ]
